[package]
name = "procpal"
version = "0.1.0"
edition = "2024"
description = "The pal daemon which executes commands parallely."
license = "MIT"
readme = "README.md"
repository = "https://github.com/ipude/pugit"
keywords = ["cli", "tui", "tmux", "zellij", "mprocs"]
categories = ["command-line-utilities"]
default-run = "procpal"

[dependencies]
ratatui = "0.30.2"
clap = {version = "4.6.1", features=["derive"]}
crossterm = "0.29.0"
textwrap = "0.16.2"
shellexpand = "3.1.2"
anyhow = "1.0.103"
shlex = "2.0.1"
interprocess = "2.4.3"
